// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFX_BOpXFcAxyGMwoAtMIpjZErbnfeis',
    appId: '1:319070275503:web:f76701629cdcdfbc71515a',
    messagingSenderId: '319070275503',
    projectId: 'expense-a8942',
    authDomain: 'expense-a8942.firebaseapp.com',
    storageBucket: 'expense-a8942.appspot.com',
    measurementId: 'G-KZ32S9HCDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyEFJ5OTjPb0nhItseposrf6Kgt9NppnU',
    appId: '1:319070275503:android:ce87c0f0d97c79a671515a',
    messagingSenderId: '319070275503',
    projectId: 'expense-a8942',
    storageBucket: 'expense-a8942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxwC5aGDACMnLuuNEeh1CRe7CqqB3B6Q',
    appId: '1:319070275503:ios:62516a5bcaf44f9371515a',
    messagingSenderId: '319070275503',
    projectId: 'expense-a8942',
    storageBucket: 'expense-a8942.appspot.com',
    iosClientId: '319070275503-dnd340b2j8lh72qoakaa4142k55uegcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxwC5aGDACMnLuuNEeh1CRe7CqqB3B6Q',
    appId: '1:319070275503:ios:75caae96616a665871515a',
    messagingSenderId: '319070275503',
    projectId: 'expense-a8942',
    storageBucket: 'expense-a8942.appspot.com',
    iosClientId: '319070275503-tkacm436kjs9tgb2mvfooie8eceh90pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
